### ISSUE TITLE
Remove console.log outputs of sun position

### ISSUE THREAD

**Issue by mattrei** [DougReeder/aframe-simple-sun-sky#2]
The component logs to the consoles output. Please remove this or hide it within a configurable component's _debug_ flag (default should be false of course).

Thank you.

**Comment by DougReeder** [comment]
Yes, I want that, too.

**Comment by DougReeder** [comment]
Done.

The flag is named “log”, so it doesn’t conflict with the built-in “debug” component.

> On Feb 19, 2019, at 9:53 AM, Matthias Treitler <notifications@github.com> wrote:
> 
> The component logs to the consoles output. Please remove this or hide it within a configurable component's debug flag (default should be false of course).
> 
> Thank you.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Doug Reeder
reeder.29@gmail.com
Recall your notes by context, with Serene Notes: https://serenenotes.hominidsoftware.com/
My gender pronouns are: he, him, his.

**Comment by mattrei** [comment]
cheers
